package org.uni.mybatis.model;

import java.util.Date;

public class Car {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.ID
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.PRODUCTION_DATE
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    private Date productionDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.MODEL_ID
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    private Integer modelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.POWER
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    private Integer power;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.CAR.TORQUE
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    private Integer torque;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.ID
     *
     * @return the value of PUBLIC.CAR.ID
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.ID
     *
     * @param id the value for PUBLIC.CAR.ID
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.PRODUCTION_DATE
     *
     * @return the value of PUBLIC.CAR.PRODUCTION_DATE
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    public Date getProductionDate() {
        return productionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.PRODUCTION_DATE
     *
     * @param productionDate the value for PUBLIC.CAR.PRODUCTION_DATE
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    public void setProductionDate(Date productionDate) {
        this.productionDate = productionDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.MODEL_ID
     *
     * @return the value of PUBLIC.CAR.MODEL_ID
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    public Integer getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.MODEL_ID
     *
     * @param modelId the value for PUBLIC.CAR.MODEL_ID
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.POWER
     *
     * @return the value of PUBLIC.CAR.POWER
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    public Integer getPower() {
        return power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.POWER
     *
     * @param power the value for PUBLIC.CAR.POWER
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    public void setPower(Integer power) {
        this.power = power;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.CAR.TORQUE
     *
     * @return the value of PUBLIC.CAR.TORQUE
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    public Integer getTorque() {
        return torque;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.CAR.TORQUE
     *
     * @param torque the value for PUBLIC.CAR.TORQUE
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    public void setTorque(Integer torque) {
        this.torque = torque;
    }
}