package org.uni.mybatis.model;

public class Dealership {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DEALERSHIP.ID
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DEALERSHIP.NAME
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.DEALERSHIP.LOCATION
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    private String location;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DEALERSHIP.ID
     *
     * @return the value of PUBLIC.DEALERSHIP.ID
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DEALERSHIP.ID
     *
     * @param id the value for PUBLIC.DEALERSHIP.ID
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DEALERSHIP.NAME
     *
     * @return the value of PUBLIC.DEALERSHIP.NAME
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DEALERSHIP.NAME
     *
     * @param name the value for PUBLIC.DEALERSHIP.NAME
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.DEALERSHIP.LOCATION
     *
     * @return the value of PUBLIC.DEALERSHIP.LOCATION
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    public String getLocation() {
        return location;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.DEALERSHIP.LOCATION
     *
     * @param location the value for PUBLIC.DEALERSHIP.LOCATION
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    public void setLocation(String location) {
        this.location = location;
    }


}