package org.uni.mybatis.model;

public class Model {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MODEL.ID
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MODEL.NAME
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MODEL.MARQUE_ID
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    private Integer marqueId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MODEL.ID
     *
     * @return the value of PUBLIC.MODEL.ID
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MODEL.ID
     *
     * @param id the value for PUBLIC.MODEL.ID
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MODEL.NAME
     *
     * @return the value of PUBLIC.MODEL.NAME
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MODEL.NAME
     *
     * @param name the value for PUBLIC.MODEL.NAME
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MODEL.MARQUE_ID
     *
     * @return the value of PUBLIC.MODEL.MARQUE_ID
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    public Integer getMarqueId() {
        return marqueId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MODEL.MARQUE_ID
     *
     * @param marqueId the value for PUBLIC.MODEL.MARQUE_ID
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    public void setMarqueId(Integer marqueId) {
        this.marqueId = marqueId;
    }
}