package org.uni.mybatis.model;

import java.util.Date;

public class Sale {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SALE.ID
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SALE.PRICE
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    private Double price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SALE.SALE_DATE
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    private Date saleDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SALE.DEALERSHIP_ID
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    private Integer dealershipId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SALE.MODEL_ID
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    private Integer modelId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SALE.SALESMAN_ID
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    private Integer salesmanId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SALE.ID
     *
     * @return the value of PUBLIC.SALE.ID
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SALE.ID
     *
     * @param id the value for PUBLIC.SALE.ID
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SALE.PRICE
     *
     * @return the value of PUBLIC.SALE.PRICE
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    public Double getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SALE.PRICE
     *
     * @param price the value for PUBLIC.SALE.PRICE
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    public void setPrice(Double price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SALE.SALE_DATE
     *
     * @return the value of PUBLIC.SALE.SALE_DATE
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    public Date getSaleDate() {
        return saleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SALE.SALE_DATE
     *
     * @param saleDate the value for PUBLIC.SALE.SALE_DATE
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    public void setSaleDate(Date saleDate) {
        this.saleDate = saleDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SALE.DEALERSHIP_ID
     *
     * @return the value of PUBLIC.SALE.DEALERSHIP_ID
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    public Integer getDealershipId() {
        return dealershipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SALE.DEALERSHIP_ID
     *
     * @param dealershipId the value for PUBLIC.SALE.DEALERSHIP_ID
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    public void setDealershipId(Integer dealershipId) {
        this.dealershipId = dealershipId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SALE.MODEL_ID
     *
     * @return the value of PUBLIC.SALE.MODEL_ID
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    public Integer getModelId() {
        return modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SALE.MODEL_ID
     *
     * @param modelId the value for PUBLIC.SALE.MODEL_ID
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    public void setModelId(Integer modelId) {
        this.modelId = modelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SALE.SALESMAN_ID
     *
     * @return the value of PUBLIC.SALE.SALESMAN_ID
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    public Integer getSalesmanId() {
        return salesmanId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SALE.SALESMAN_ID
     *
     * @param salesmanId the value for PUBLIC.SALE.SALESMAN_ID
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    public void setSalesmanId(Integer salesmanId) {
        this.salesmanId = salesmanId;
    }
}