package org.uni.mybatis.model;

public class Salesman {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SALESMAN.ID
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SALESMAN.FIRST_NAME
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    private String firstName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.SALESMAN.LAST_NAME
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    private String lastName;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SALESMAN.ID
     *
     * @return the value of PUBLIC.SALESMAN.ID
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SALESMAN.ID
     *
     * @param id the value for PUBLIC.SALESMAN.ID
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SALESMAN.FIRST_NAME
     *
     * @return the value of PUBLIC.SALESMAN.FIRST_NAME
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SALESMAN.FIRST_NAME
     *
     * @param firstName the value for PUBLIC.SALESMAN.FIRST_NAME
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.SALESMAN.LAST_NAME
     *
     * @return the value of PUBLIC.SALESMAN.LAST_NAME
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.SALESMAN.LAST_NAME
     *
     * @param lastName the value for PUBLIC.SALESMAN.LAST_NAME
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }
}