package org.uni.mybatis.dao;

import java.util.List;

import org.mybatis.cdi.Mapper;
import org.uni.mybatis.model.Sale;

@Mapper
public interface SaleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SALE
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SALE
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    int insert(Sale record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SALE
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    Sale selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SALE
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    List<Sale> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SALE
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    int updateByPrimaryKey(Sale record);
}