package org.uni.mybatis.dao;

import java.util.List;

import org.mybatis.cdi.Mapper;
import org.uni.mybatis.model.Salesman;

@Mapper
public interface SalesmanMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SALESMAN
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SALESMAN
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    int insert(Salesman record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SALESMAN
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    Salesman selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SALESMAN
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    List<Salesman> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.SALESMAN
     *
     * @mbg.generated Mon Apr 05 18:35:58 EEST 2021
     */
    int updateByPrimaryKey(Salesman record);
}